[build]
  base = "clients/"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://snip-sync.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 